#-------------------------------
# General Site Settings

title: Manta Innovations Ltd
logo: logo_small.png
email: sales@manta-innovations.co.uk
phone: +44 7969 316 432
address: London, SE8 3FW

menu:
- {name: About, link: '/about'}
- {name: Blog, link: '/blog'}
- {name: Contact, link: '/contact'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: UA-121436590-1


#-------------------------------
# Comment Section (Disqus)

# disqus-identifier: jhole89-github


#-------------------------------
# Hero Section

hero:
  hero-title: Manta Innovations Ltd <font size="5"><br>Big Data, DevOps, and Cloud consultancy solutions</font>

social:
- {icon: "ti-github", link: "https://github.com/jhole89"}
- {icon: "ti-twitter", link: "https://twitter.com/jhole89"}
- {icon: "ti-stack-overflow", link: "https://stackoverflow.com/users/5094147"}
- {icon: "ti-linkedin ", link: "https://www.linkedin.com/in/joellutman"}


#-------------------------------
# About (Section and Page)

# About Section
blurb: "Hi, I'm Joel, a software engineer, big data veteren, ML enthusiast, infrastructure specialist, serverless fanboy,
and gaming hobbiest. I enjoy designing and iterating solutions for new challenges with fast feedback loops. I don't
buy in to traditional release cycles, but believe in automating manual processes to ensure every commit is release worthy
and provides value. I believe in flat structures, openness across teams, sustainable coding, best practice, and no
compromises on quality."


blurb-btn-link: '/about'
blurb-btn-name: know more


# About Page

# Work Process Section
work-process:
  - title : "Understand and Plan"
    icon : "assets/images/icons/plan.png"
    content : "Before trying to solve we need to understand what we are aiming to achieve, only then can we establish what patterns would be best suited for the problem we are trying to solve."

  - title : "Design and Develop"
    icon : "assets/images/icons/design.png"
    content : "Once we understand the problem, we can start designing any architecture and developing a solution. Iterating is key here and we should establish a fast feedback loop with users and automated systems."
    
  - title : "Deliver and Iterate"
    icon : "assets/images/icons/print.png"
    content : "No one likes long delivery cycles, least of all developers. Short and frequently cycles gives us the best way to gain feedback, flush bugs, and improve. No system if perfect, but we can try."

#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Big Data & ML, color: '#f44336', value: '90%'}
- {name: Cloud Architecture, color: '#FF9800', value: '80%'}
- {name: DevOps, color: '#8BC34A', value: '75%'}
- {name: Web Apps, color: '#03A9F4', value: '70%'}


#-------------------------------
# Experience Section

experience-title: Experience
experience:
- {name: Data Scientist & Engineer, icon: 'icon-1.png', date: 'May 2015 - Apr 2018', organization: 'BAE SYSTEMS AI'}
- {name: Senior Python Developer, icon: 'icon-2.png', date: 'Mar 2018 - Feb 2019', organization: 'LIMEJUMP'}
- {name: Director & Software Engineer, icon: 'icon-3.png', date: 'Jan 2019 - Present', organization: 'MANTA INNOVATIONS LTD'}


#-------------------------------
# Education Section

education-title: Education
education:
- {name: Masters in Mathematical Biology, date: '2012', organization: 'University of Bath'}
- {name: 1st Class Honours in Mathematics, date: '2010', organization: 'University of Sussex'}
- {name: "ABB in A-Level Maths, Further Maths, Law", date: '2007', organization: 'Worthing Sixth Form College'}
- {name: 10 GCSE's A-C, date: '2005', organization: 'Chatsmore Catholic High School'}


#-------------------------------
# Services Section

services-title: Services
services:
- {
    name: Big Data,
    icon: ti-server,
    description: "Big data solutions & frameworks for large scale distributed data processing and analytics; based on Apache Spark.",
    active: # Add true to select section
  }
- {
    name: Machine Learning,
    icon: ti-panel,
    description: "Machine Learning solutions from simple regression through to Neural Networks; based on SKLearn and TensorFlow.",
    active: true # Add true to select section
  }
- {
    name: Cloud Architecture,
    icon: ti-cloud,
    description: "Serverless cloud solutions reducing the risk of security vulnerabilities and platform outages; scripted with Terraform.",
    active: # Add true to select section
  }
- {
  name: DevOps & Platform Eng,
  icon: ti-infinite,
  description: "Automated DevOps solutions following best practice to ensure bugs never touch live systems; using docker and kubernetes.",
  active: true # Add true to select section
  }
- {
  name: Web Apps,
  icon: ti-palette,
  description: "Full stack web apps from simple static websites through to dynamic sites backed by SQL & NoSQL databases.",
  active: # Add true to select section
  }
- {
  name: Review & Upskill,
  icon: ti-check-box,
  description: "Independent code appraisal and vulnerability reviews. Take it further by ensuring your teams know the latest tools and techniques.",
  active: true # Add true to select section
  }



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/tensorflow_android.png"
    url: "https://github.com/jhole89/tensorflow-classifier-android"
    
  - image : "assets/images/portfolio/neural_network.png"
    url: "https://github.com/jhole89/convnet-image-classifier"
    
  - image : "assets/images/portfolio/tf_cancer.png"
    url: "https://github.com/jhole89/classifying-cancer"


# Portfolio Page
portfolio-label:
- {
    title : "DATA",
    type : "data"
  }
- {
    title : "ARCHITECTURE",
    type : "architecture"
  }
- {
    title : "WEB",
    type : "web"
  }

portfolio-items:

  - image : "assets/images/portfolio/crud.jpg"
    url: "https://github.com/jhole89/simple-CRUD-app"
    portfolio-type:
      - type: "web"

  - image : "assets/images/portfolio/github_site.png"
    url: "https://github.com/jhole89/jhole89.github.io"
    portfolio-type:
      - type: "web"
      
  - image : "assets/images/portfolio/replate.jpg"
    url: "https://github.com/jhole89/Leftovers"
    portfolio-type:
      - type: "data"
      - type: "architecture"
      
  - image : "assets/images/portfolio/tensorflow_android.png"
    url: "https://github.com/jhole89/tensorflow-classifier-android"
    portfolio-type:
      - type: "data"
      - type: "architecture"
      
  - image : "assets/images/portfolio/djikstra.png"
    url: "https://github.com/jhole89/osm-router"
    portfolio-type:
      - type: "data"
      
  - image : "assets/images/portfolio/neural_network.png"
    url: "https://github.com/jhole89/convnet-image-classifier"
    portfolio-type:
      - type: "data"
      
  - image : "assets/images/portfolio/chatbot.png"
    url: "https://github.com/jhole89/you-talkin-to-me"
    portfolio-type:
      - type: "data"
      - type: "web"
      
  - image : "assets/images/portfolio/tf_cancer.png"
    url: "https://github.com/jhole89/classifying-cancer"
    portfolio-type:
      - type: "data"
      
  - image : "assets/images/portfolio/twitter-analytics.png"
    url: "https://github.com/jhole89/tweet-analyser"
    portfolio-type:
      - type: "data"

  - image : "assets/images/portfolio/data_sci_env.png"
    url: "https://github.com/jhole89/DataScienceDevEnvironment"
    portfolio-type:
      - type: "architecture"


#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: sales@manta-innovations.co.uk